# Generated by Django 5.1.4 on 2024-12-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
